export const CROSSWORD_LIST_REQUEST = "CROSSWORD_LIST_REQUEST";
export const CROSSWORD_LIST_SUCCESS = "CROSSWORD_LIST_SUCCESS";
export const CROSSWORD_LIST_FAIL = "CROSSWORD_LIST_FAIL";

export const CROSSWORD_CREATE_REQUEST = "CROSSWORD_CREATE_REQUEST";
export const CROSSWORD_CREATE_SUCCESS = "CROSSWORD_CREATE_SUCCESS";
export const CROSSWORD_CREATE_FAIL = "CROSSWORD_CREATE_FAIL";

export const CROSSWORD_DELETE_REQUEST = "CROSSWORD_DELETE_REQUEST";
export const CROSSWORD_DELETE_SUCCESS = "CROSSWORD_DELETE_SUCCESS";
export const CROSSWORD_DELETE_FAIL = "CROSSWORD_DELETE_FAIL";

export const CROSSWORD_UPDATE_REQUEST = "CROSSWORD_UPDATE_REQUEST";
export const CROSSWORD_UPDATE_SUCCESS = "CROSSWORD_UPDATE_SUCCESS";
export const CROSSWORD_UPDATE_FAIL = "CROSSWORD_UPDATE_FAIL";
