export const FILL_BLANK_LIST_REQUEST = "FILL_BLANK_LIST_REQUEST";
export const FILL_BLANK_LIST_SUCCESS = "FILL_BLANK_LIST_SUCCESS";
export const FILL_BLANK_LIST_FAIL = "FILL_BLANK_LIST_FAIL";

export const FILL_BLANK_CREATE_REQUEST = "FILL_BLANK_CREATE_REQUEST";
export const FILL_BLANK_CREATE_SUCCESS = "FILL_BLANK_CREATE_SUCCESS";
export const FILL_BLANK_CREATE_FAIL = "FILL_BLANK_CREATE_FAIL";

export const FILL_BLANK_DELETE_REQUEST = "FILL_BLANK_DELETE_REQUEST";
export const FILL_BLANK_DELETE_SUCCESS = "FILL_BLANK_DELETE_SUCCESS";
export const FILL_BLANK_DELETE_FAIL = "FILL_BLANK_DELETE_FAIL";

export const FILL_BLANK_UPDATE_REQUEST = "FILL_BLANK_UPDATE_REQUEST";
export const FILL_BLANK_UPDATE_SUCCESS = "FILL_BLANK_UPDATE_SUCCESS";
export const FILL_BLANK_UPDATE_FAIL = "FILL_BLANK_UPDATE_FAIL";
