export const LIVE_SESSION_CREATE_REQUEST = "LIVE_SESSION_CREATE_REQUEST";
export const LIVE_SESSION_CREATE_SUCCESS = "LIVE_SESSION_CREATE_SUCCESS";
export const LIVE_SESSION_CREATE_FAIL = "LIVE_SESSION_CREATE_FAIL";

export const TEACHER_LIVE_SESSIONS_REQUEST = "TEACHER_LIVE_SESSIONS_REQUEST";
export const TEACHER_LIVE_SESSIONS_SUCCESS = "TEACHER_LIVE_SESSIONS_SUCCESS";
export const TEACHER_LIVE_SESSIONS_FAIL = "TEACHER_LIVE_SESSIONS_FAIL";

export const STUDENT_LIVE_SESSIONS_REQUEST = "STUDENT_LIVE_SESSIONS_REQUEST";
export const STUDENT_LIVE_SESSIONS_SUCCESS = "STUDENT_LIVE_SESSIONS_SUCCESS";
export const STUDENT_LIVE_SESSIONS_FAIL = "STUDENT_LIVE_SESSIONS_FAIL";

export const LIVE_SESSION_CREATE_RESET = "LIVE_SESSION_CREATE_RESET";

export const LIVE_SESSION_DELETE_REQUEST = "LIVE_SESSION_DELETE_REQUEST";
export const LIVE_SESSION_DELETE_SUCCESS = "LIVE_SESSION_DELETE_SUCCESS";
export const LIVE_SESSION_DELETE_FAIL = "LIVE_SESSION_DELETE_FAIL";