export const MCQ_ATTEMPT_REQUEST = "MCQ_ATTEMPT_REQUEST";
export const MCQ_ATTEMPT_SUCCESS = "MCQ_ATTEMPT_SUCCESS";
export const MCQ_ATTEMPT_FAIL = "MCQ_ATTEMPT_FAIL";

// MY ATTEMPTS

export const MCQ_ATTEMPT_LIST_REQUEST = "MCQ_ATTEMPT_LIST_REQUEST";
export const MCQ_ATTEMPT_LIST_SUCCESS = "MCQ_ATTEMPT_LIST_SUCCESS";
export const MCQ_ATTEMPT_LIST_FAIL = "MCQ_ATTEMPT_LIST_FAIL";

// MCQ RESULTS

export const MCQ_RESULTS_REQUEST = "MCQ_RESULTS_REQUEST";
export const MCQ_RESULTS_SUCCESS = "MCQ_RESULTS_SUCCESS";
export const MCQ_RESULTS_FAIL = "MCQ_RESULTS_FAIL";
