export const REVIEW_CREATE_REQUEST = "REVIEW_CREATE_REQUEST";
export const REVIEW_CREATE_SUCCESS = "REVIEW_CREATE_SUCCESS";
export const REVIEW_CREATE_FAIL = "REVIEW_CREATE_FAIL";
export const REVIEW_CREATE_RESET = "REVIEW_CREATE_RESET";

export const REVIEW_LIST_REQUEST = "REVIEW_LIST_REQUEST";
export const REVIEW_LIST_SUCCESS = "REVIEW_LIST_SUCCESS";
export const REVIEW_LIST_FAIL = "REVIEW_LIST_FAIL";

export const REVIEW_ALL_REQUEST = "REVIEW_ALL_REQUEST";
export const REVIEW_ALL_SUCCESS = "REVIEW_ALL_SUCCESS";
export const REVIEW_ALL_FAIL = "REVIEW_ALL_FAIL";

export const REVIEW_APPROVE_REQUEST = "REVIEW_APPROVE_REQUEST";
export const REVIEW_APPROVE_SUCCESS = "REVIEW_APPROVE_SUCCESS";
export const REVIEW_APPROVE_FAIL = "REVIEW_APPROVE_FAIL";

export const REVIEW_DELETE_REQUEST = "REVIEW_DELETE_REQUEST";
export const REVIEW_DELETE_SUCCESS = "REVIEW_DELETE_SUCCESS";
export const REVIEW_DELETE_FAIL = "REVIEW_DELETE_FAIL";
