export const WORD_MATCH_LIST_REQUEST = "WORD_MATCH_LIST_REQUEST";
export const WORD_MATCH_LIST_SUCCESS = "WORD_MATCH_LIST_SUCCESS";
export const WORD_MATCH_LIST_FAIL = "WORD_MATCH_LIST_FAIL";

export const WORD_MATCH_CREATE_REQUEST = "WORD_MATCH_CREATE_REQUEST";
export const WORD_MATCH_CREATE_SUCCESS = "WORD_MATCH_CREATE_SUCCESS";
export const WORD_MATCH_CREATE_FAIL = "WORD_MATCH_CREATE_FAIL";

export const WORD_MATCH_DELETE_REQUEST = "WORD_MATCH_DELETE_REQUEST";
export const WORD_MATCH_DELETE_SUCCESS = "WORD_MATCH_DELETE_SUCCESS";
export const WORD_MATCH_DELETE_FAIL = "WORD_MATCH_DELETE_FAIL";

export const WORD_MATCH_UPDATE_REQUEST = "WORD_MATCH_UPDATE_REQUEST";
export const WORD_MATCH_UPDATE_SUCCESS = "WORD_MATCH_UPDATE_SUCCESS";
export const WORD_MATCH_UPDATE_FAIL = "WORD_MATCH_UPDATE_FAIL";
